### ISSUE TITLE
Error on http://example.gnap.io/#/examples

### ISSUE THREAD

**Issue by koenmetsu** [infrabel/docs-gnap#28]
"Error: event is not defined
b/<@http://example.gnap.io/js/gnap/validate.directive.min.js:1:139
Bc/this.$get</k.prototype.$digest@http://example.gnap.io/js/angular/angular.min.js:2:24507
Bc/this.$get</k.prototype.$apply@http://example.gnap.io/js/angular/angular.min.js:2:26031
i@http://example.gnap.io/js/angular/angular.min.js:2:4744
r@http://example.gnap.io/js/angular/angular.min.js:2:7154
_b/</w.onreadystatechange@http://example.gnap.io/js/angular/angular.min.js:2:7730
" undefined angular.min.js:2:15070
e/<() angular.min.js:2
Tb/this.$get</<() angular.min.js:2
b/<() gnap.min.js:1
Bc/this.$get</k.prototype.$digest() angular.min.js:2
Bc/this.$get</k.prototype.$apply() angular.min.js:2
i() angular.min.js:2
r() angular.min.js:2
_b/</w.onreadystatechange() angular.min.js:2

**Comment by koenmetsu** [comment]
Browser: Firefox Developer Edition
Win8.1

**Comment by CumpsD** [comment]
Theme issue, moved to https://github.com/infrabel/themes-gnap/issues/112
